### ISSUE TITLE
Add parameter "--insecure-skip-tls-verify"

### ISSUE THREAD

**Issue by eatsleepandcode** [endocode/ausroller#20]
In some environments a self-signed certificate is used for k8s.
kubectl has a parameter  --insecure-skip-tls-verify. One can workaround on a local machine with aliases or shellscript, but it would get annoying to do that on several machines/environments/jenkinses.
So be better to have that as ausroller parameter.

**Comment by mattthias** [comment]
This is a very bad idea as it encourages the bad behavior of ignoring invalid certificates.

But as we discussed in person we should find a way to allow this with Ausroller.

**Comment by jmastr** [comment]
I suggest to set `--insecure-skip-tls-verify=true` globally per cluster:

- `kubectl config set-cluster cluster --server=https://${API_SERVER_IP}:${API_SERVER_PORT} --insecure-skip-tls-verify=true`

That way the user is in charge. If we do it that way, we should update the `README.md` accordingly.

**Comment by eatsleepandcode** [comment]
@jmastr: Yes. That sounds like a good idea. I like that. Didn't know that we can do it in that way.

**Comment by jmastr** [comment]
Let us take this issue to track the patch for the `README.md`.
